### ISSUE TITLE
Move scripts into a `books` subfolder

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/jquery-ajax-delete#3]
For consistency with `api-token-auth`.

`assets/scripts/ui.js` should be moved to `assets/scripts/books/ui.js`. Same for other scripts.

**Comment by RealWeeks** [comment]
This is resolved in the latest commit, I messed erred here

**Comment by payne-chris-r** [comment]
@jrhorn424 @J-Weeks same here. Ok to close?
