### ISSUE TITLE
Move handlers into `events.js`

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/jquery-ajax-delete#4]
Any handlers defined currently in `assets/scripts/index.js` should be moved to an appropriate folder as `events.js`. For example, `assets/scripts/books/events.js`.

**Comment by RealWeeks** [comment]
This is resolved in the latest commit, I messed erred here

**Comment by payne-chris-r** [comment]
@J-Weeks and @jrhorn424 ok to close?
