### ISSUE TITLE
Fix spelling in book-destory.sh

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/jquery-ajax-delete#7]
Should be book-destroy.sh

**Comment by danman01** [comment]
These .sh files are actually dropping the `book` prefix in other repos in this series: https://github.com/ga-wdi-boston/jquery-ajax-get-element/issues/9 

Can we close this issue @payne-chris-r 

*edit* I see this was for a typo. That has been fixed.

**Comment by raq929** [comment]
Confirmed by review.
